<?php
// This file is auto-generated by the bot. Do not edit manually.
// Your Developer API Key is configured below.

define('HOST_BOT_API_KEY', '{USER_API_KEY_PLACEHOLDER}');

if (!function_exists('setBotWebhook')) {
    /**
     * Sets the webhook for a given bot token and path.
     * The API Key is automatically read from the HOST_BOT_API_KEY constant.
     *
     * @param string $botToken The token of the bot to set the webhook for.
     * @param string $botPath The relative path to the bot's PHP file within your hosting space.
     * @return array|null The response from the server or null on connection failure.
     */
    function setBotWebhook(string $botToken, string $botPath): ?array {


        $apiKey = HOST_BOT_API_KEY;
        $endpoint = "{INTERNAL_API_ENDPOINT}";

        $payload = [
            'action'  => 'set_webhook',
            'api_key' => $apiKey,
            'payload' => [
                'new_bot_token' => $botToken,
                'new_bot_path'  => $botPath,
            ]
        ];

        $ch = curl_init($endpoint);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER     => ['Content-Type: application/json'],
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => json_encode($payload),
            CURLOPT_TIMEOUT        => 20,
            CURLOPT_CONNECTTIMEOUT => 10,
        ]);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error    = curl_error($ch);
        curl_close($ch);

        if ($response === false) {
            return ['error' => 'Connection failed', 'curl_error' => $error];
        }

        return [
            'status_code' => $httpCode,
            'body'        => json_decode($response, true) ?? $response
        ];
    }
}
