display_errors = On
error_reporting = E_ALL

disable_functions = stream_wrapper_restore,stream_wrapper_register,unserialize,ini_set,glob,proc_terminate,fsockopen,stream_socket_client,ini_get,get_cfg_var,create_function,getenv,get_defined_vars,get_defined_functions,get_loaded_extensions,get_current_user,ini_get_all,escapeshellarg,assert,eval,exec,passthru,shell_exec,system,proc_open,popen,parse_ini_file,show_source,pcntl_exec,pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,putenv,apache_setenv,dl,posix_kill,posix_mkfifo,posix_setpgid,posix_setsid,posix_setuid,ini_alter,ini_restore,openlog,syslog,highlight_file,phpinfo,readlink,symlink,link

user_ini.filename =
allow_url_include = Off
